### ISSUE TITLE
login with twitter

### ISSUE THREAD

**Issue by bjelline** [learnery/learnery#12]
as a visitor, 
i canregister on the site with twitter, 
so i can log in without a password in the future

**Comment by drblinken** [comment]
das funktioniert noch nicht: 
DETAIL:  Key (email)=() already exists.
es geht um den fall wenn ich mich schon vorher mal mit der e-mail die twitter liefert
angemeldet hab.  ich glaub den müsste man dann mit sinnvoller fehlermeldung
zurück weisen.
und dann gibts ne neue story für: ich bin bei learnery eingeloggt und füge eine authentisierungs-methode hinzu.
