### ISSUE TITLE
german / I18n

### ISSUE THREAD

**Issue by bjelline** [learnery/learnery#13]
as an organizer, 
I can configure the whole app to use german instead of english
so i can hold events for german-only-speakers

**Comment by drblinken** [comment]
I18n. Vielleicht lieber bald als später einbauen?

**Comment by bjelline** [comment]
ja!  ist so schon viel arbeit bei den tests

**Comment by drblinken** [comment]
Ich würde es in der nächsten woche machen, ok? Hier ein paar links für mich: 
https://github.com/htw-rails/I18n
http://ruby-i18n.org

**Comment by bjelline** [comment]
noch links: 
https://github.com/Locale/localeapp
http://www.railway.at/articles/2009/09/12/using-cucumber-to-test-a-multilingual-app/

**Comment by bjelline** [comment]
ich hatte beim fliegen ein paar stunden wartezeit und hab mal angefangen im i18n. siehe branch
feature-i18n und https://github.com/learnery/learnery-theme-de

**Comment by drblinken** [comment]
cool, alle texte mit t :) - hast Du eine Idee, wie die sprache dann umgestellt werden soll? Über User Profile oder einfach über routes/links auf der Seite? oder per event?
oder soll es wirklich nur einmalig per deployment eingestellt werden?

**Comment by bjelline** [comment]
ich denk fürn anfang reicht mal: per theme umstellen.   ich hätte dafür unter lib/learnery/theme/version.rb schon die constante  SITE_LOCALE  gesetzt - aber die bewirkt noch nix

**Comment by bjelline** [comment]
long done
