### ISSUE TITLE
mark participation as confirmed/pending/canceled

### ISSUE THREAD

**Issue by titanoboa** [learnery/learnery#18]
As an admin, I want to be able to change the status of accepted applicants to 'participation confirmed' or 'participation canceled'

**Comment by drblinken** [comment]
What is the relation to the rsvp? What would be the workflow? Does the rsvp even make sense with this or would it rather replace this?

**Comment by titanoboa** [comment]
workflow: application received (pending) -> application rejected or accepted -> if accepted: (some time passes) -> participants confirm or cancel their participation

**Comment by drblinken** [comment]
Sounds as if it will be something replacing the rsvp concept in some way rather than extending it.

**Comment by bjelline** [comment]
i've started converting the rsvp to differnt classes with different state machines, i hope to be able to implenent this issue based on that
