### ISSUE TITLE
Make Learnery an Engine

### ISSUE THREAD

**Issue by drblinken** [learnery/learnery#28]
I open an issue here do document the work on it.

**Comment by drblinken** [comment]
The I18n keys in the Rsvp Hierarchy are all the same: learnery/rsvp
2.0.0p0 :008 > Learnery::Rsvp.model_name
 => #<ActiveModel::Name:0x007fc383859280 @name="Learnery::Rsvp", @unnamespaced="Rsvp", @klass=Learnery::Rsvp(id: integer, answer: string, user_id: integer, event_id: integer, created_at: datetime, updated_at: datetime, type: string, asked_at: datetime, confirmed_at: datetime), @singular="learnery_rsvp", @plural="learnery_rsvps", @element="rsvp", @human="Rsvp", @collection="learnery/rsvps", @param_key="rsvp", @i18n_key=:"learnery/rsvp", @route_key="rsvps", @singular_route_key="rsvp">
2.0.0p0 :009 > Learnery::OpenRsvp.model_name
 => #<ActiveModel::Name:0x007fc383859280 @name="Learnery::Rsvp", @unnamespaced="Rsvp", @klass=Learnery::Rsvp(id: integer, answer: string, user_id: integer, event_id: integer, created_at: datetime, updated_at: datetime, type: string, asked_at: datetime, confirmed_at: datetime), @singular="learnery_rsvp", @plural="learnery_rsvps", @element="rsvp", @human="Rsvp", @collection="learnery/rsvps", @param_key="rsvp", @i18n_key=:"learnery/rsvp", @route_key="rsvps", @singular_route_key="rsvp">
2.0.0p0 :010 >

**Comment by bjelline** [comment]
new repositories + demo sites for example apps created, 
switch to engin is done now.
