### ISSUE TITLE
assets:precompile fails

### ISSUE THREAD

**Issue by floriankrueger** [learnery/learnery#31]
Rails fails to precompile `style.css.less` due to `@navbarBackground` being undefined. 
Recreate the issue by running `rake assets:precompile`:

```
rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
variable @navbarBackground is undefined
  (in /Users/fkrueger/Playground/learnery-default/app/assets/stylesheets/style.css.less)
```

**Comment by bjelline** [comment]
this happens when you include style.less.css directly from application.css.

style.less.css  is included by bootstrap_and_overrides.css.less, only
there are the variables visible

**Comment by bjelline** [comment]
fixed in all the example apps, for example

https://github.com/learnery/learnery-webdev/blob/master/app/assets/stylesheets/application.css
