### ISSUE TITLE
upgrade, test and deploy all example apps after learnery engine changes

### ISSUE THREAD

**Issue by bjelline** [learnery/learnery#36]
here's the shell script i use for now: 
https://gist.github.com/bjelline/6048466

**Comment by drblinken** [comment]
I've wrote some shell scripts to update the deployment and learnery versions in all themes. See
https://github.com/learnery/project-automation/tree/master/bin - as there is no way define dependent builds in travis right now. I reason the "way to go" is to have a dev actively updating the version of learnery in a theme, and this scripts make it easy for our four default themes.
